### ISSUE TITLE
[Argo runtime] Storing the output artifacts doesn't work on older versions of Argo v3

### ISSUE THREAD

**Issue by larribas** [larribas/dagger#37]
#### What happened:

While trying to run Argo workflows generated by the Argo runtime in our cluster, we encountered the following error in the "wait" container:

> Error (exit code 1): failed to chroot to main filesystem: operation not permitted

After some troubleshooting, we found the root cause to be the final slash in the `volumeMount.0.mountPath`.

We believe this error may be related to this bug in Argo: https://github.com/argoproj/argo-workflows/issues/5520

To increase compatibility with older versions, we would like to remove the final slash.

#### What you expected to happen:

We expected the outputs to be saved successfully by the wait container.

#### How to reproduce it (as minimally and precisely as possible):

Running this manifest with the version of Kubernetes and Argo specified below:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: troubleshoot-outputs-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
        - name: generate-output
          template: generate-output

  - name: generate-output
    outputs:
      artifacts:
      - name: return_value
        path: /tmp/outputs/myfile
    volumes:
    - emptyDir: {}
      name: outputs
    script:
      image: python:alpine3.6
      command: [python]
      volumeMounts:
      - mountPath: /tmp/outputs/
        name: outputs
      source: |
        import os
        with open(os.path.join("/tmp/outputs", "myfile"), "w") as f:
          f.write("...")
```

#### Environment:
- Dagger version: 0.2.0
- Python version: 3.8
- Argo version: 3.0.2
- Argo Exec container image: `quay.io/argoproj/argoexec:v3.0.2`
